### ISSUE TITLE
How to see what error have occured during action execution?

### ISSUE THREAD

**Issue by fedochet** [peter-evans/create-or-update-project-card#32]
Hi! I am having trouble debugging your action: it seems that no error output is shown when error happens.

![image](https://user-images.githubusercontent.com/8393617/109147345-f2019100-7775-11eb-8d57-096dcf46fa03.png)

Is it by design? Maybe there is some flag to enable to see more verbose output?

**Comment by peter-evans** [comment]
Hi @fedochet 

You can [enable step debug messages](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) by adding a the secret `ACTIONS_STEP_DEBUG` with value `true`.

What you have shown in the screenshot is just the metadata for the step itself. Usually the error will be on the lines after this. I can't see below line 10 to check what the output is.

**Comment by fedochet** [comment]
There are nothing to see, unfortunately:
![image](https://user-images.githubusercontent.com/8393617/109288646-35bbcf80-7836-11eb-9067-d9b5c2bacf4a.png)

I will try to use the flag you've mentioned, thanks!

**Comment by fedochet** [comment]
Currently I am using your action like this:

```
      - name: Add Pull Request to project
        uses: peter-evans/create-or-update-project-card@v1.1.4
        with:
          project-location: csc-java-course
          project-number: 2
          column-name: Не проверено
          issue-number: 1
          repository: csc-java-course/csc-java-course-new-assignment-template-test-3
```

I am seeing this log: 

```
##[debug]Loading env
Run peter-evans/create-or-update-project-card@v1.1.4
  with:
    project-location: csc-java-course
    project-number: 2
    column-name: Не проверено
    issue-number: 1
    repository: csc-java-course/csc-java-course-new-assignment-template-test-3
    token: ***
##[debug]Inputs: {
##[debug]  token: '***',
##[debug]  projectLocation: 'csc-java-course',
##[debug]  projectNumber: 2,
##[debug]  projectName: '',
##[debug]  columnName: 'Не проверено',
##[debug]  repository: 'csc-java-course/csc-java-course-new-assignment-template-test-3',
##[debug]  issueNumber: 1
##[debug]}
##[debug]RequestError [HttpError]
##[debug]    at /home/runner/work/_actions/peter-evans/create-or-update-project-card/v1.1.4/dist/index.js:3655:23
##[debug]    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
##[debug]  name: 'HttpError',
##[debug]  status: 500,
##[debug]  headers: {
##[debug]    'access-control-allow-origin': '*',
##[debug]    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
##[debug]    connection: 'close',
##[debug]    'content-length': '0',
##[debug]    'content-security-policy': "default-src 'none'",
##[debug]    'content-type': 'application/json; charset=utf-8',
##[debug]    date: 'Sat, 27 Feb 2021 10:28:47 GMT',
##[debug]    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
##[debug]    server: 'GitHub.com',
##[debug]    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
##[debug]    vary: 'Accept-Encoding, Accept, X-Requested-With',
##[debug]    'x-content-type-options': 'nosniff',
##[debug]    'x-frame-options': 'deny',
##[debug]    'x-github-media-type': 'github.inertia-preview; format=json, github.inertia-preview; format=json',
##[debug]    'x-github-request-id': '0401:14A6:66FDD8:CF46B8:603A1EDF',
##[debug]    'x-ratelimit-limit': '1000',
##[debug]    'x-ratelimit-remaining': '998',
##[debug]    'x-ratelimit-reset': '1614425327',
##[debug]    'x-ratelimit-used': '2',
##[debug]    'x-xss-protection': '1; mode=block'
##[debug]  },
##[debug]  request: {
##[debug]    method: 'GET',
##[debug]    url: 'https://api.github.com/orgs/csc-java-course/projects?per_page=100',
##[debug]    headers: {
##[debug]      accept: 'application/vnd.github.inertia-preview+json,application/vnd.github.inertia-preview+json',
##[debug]      'user-agent': 'octokit-core.js/3.1.0 Node.js/12.13.1 (Linux 5.4; x64)',
##[debug]      authorization: 'token [REDACTED]'
##[debug]    },
##[debug]    request: { agent: [Agent], hook: [Function: bound bound register] }
##[debug]  }
##[debug]}
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Add Pull Request to project
```

I cannot understand what is going wrong, and why there is a `RequestError`

**Comment by fedochet** [comment]
I have been able to successfully use it when the project was the part of the repo, but I need to add the PR to the organisation-level project

Also, I've tried to use your action locally (by downloading the code and hardcoding the config-values), and it seems to work as expected

**Comment by fedochet** [comment]
Maybe the porblem is that the default github token is not permissive enough for this action to add PR to the priavate org's project

**Comment by peter-evans** [comment]
Yes, you need to use a PAT. Please see this section of the readme. 

https://github.com/peter-evans/create-or-update-project-card#create-a-card-in-an-organization-or-user-project

**Comment by fedochet** [comment]
I haven't noticed that, thank you!

**Comment by peter-evans** [comment]
Assuming this is resolved now, so closing the issue.
