### ISSUE TITLE
Need better error messages

### ISSUE THREAD

**Issue by tijlleenders** [peter-evans/create-or-update-project-card#62]
Hey Peter, great job with this project.

I've tried using it but am running into some trouble.
Don't know if I'm looking in the right place but I couldn't find a clear error message.

Here's my experience:
Tried playing with the yaml format.
Tried increasing the scope of the token.
Tried using a repository project instead of a user project.
So this is the new workflow file:
```
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: 1
          column-name: Backlog
          issue-number: ${{ github.event.issue.number }}
```
Somehow it is still showing the token: ** even though I removed it in the invocation...
![image](https://user-images.githubusercontent.com/44887755/161826095-0d68950c-9ee7-42aa-be37-b1e134520ad7.png)

Added debug logging to action workflow by setting ACTIONS_RUNNER_DEBUG secret to true and downloading log archive.
Found this in runner-diagnostic-logs folder:
```
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] Process started with process id 1523, waiting for process exit.
[2022-04-05 18:26:17Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] Finished process 1523 with exit code 1, and elapsed time 00:00:00.4126040.
[2022-04-05 18:26:17Z INFO CreateStepSummaryCommand] Step Summary is disabled; skipping attachment upload
[2022-04-05 18:26:17Z INFO StepsRunner] Step result: Failed
[2022-04-05 18:26:17Z INFO ExecutionContext] Publish step telemetry for current step {
  "action": "peter-evans/create-or-update-project-card",
  "ref": "v2",
  "type": "node16",
  "stage": "Main",
  "stepId": "745e91ee-9815-5c93-c9b0-e2d032c829c4",
  "hasPreStep": false,
  "hasPostStep": false,
  "result": "failed",
  "errorMessages": [],
  "executionTimeInSeconds": 1
}.
```
Since there is no clear error message I'm giving up.

**Comment by peter-evans** [comment]
Hi @tijlleenders 

What you are looking at there is not the run log, it's the log of the Actions runner. That's why you can't see the output of the workflow. The actions runner is attached to a repository to fetch jobs. You need to look in the repositories `Actions` tab to see the log output of each run.

For example, you can look at the `Actions` tab in this repository and see all the workflow logs. You need to do the same to see the logs.
https://github.com/peter-evans/create-or-update-project-card/actions

**Comment by tijlleenders** [comment]
Thanks for responding Peter!

I do see a difference between the ```Actions``` tab output in your repo vs my repo.
**How do I enable the ##debug in the log settings?**

My repo run log output (without ##debug):
![image](https://user-images.githubusercontent.com/44887755/161898461-98089fa0-ba92-413e-9572-d5786938c1df.png)

Your repo run log output:
![image](https://user-images.githubusercontent.com/44887755/161898532-d7bfe14f-360b-4bdb-891f-0ff714b21e6f.png)


**In the downloaded logs I found three logs types:**
![image](https://user-images.githubusercontent.com/44887755/161899264-580f7b42-e029-472b-ab28-f1fb203031d2.png)
- createCard contains what I see on web UI (without ##debug)
- runner-diagnostics-logs conatins a Runner file and a Worker file.
Only the Runner file contains an error - and it looks like this is unrelated to your code...:
```
[2022-04-05 18:26:12Z ERR  JobNotification] Connection to monitor port 49100 failed!
[2022-04-05 18:26:12Z ERR  JobNotification] System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused [::ffff:127.0.0.1]:49100
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at GitHub.Runner.Common.JobNotification.ConnectMonitor(String monitorSocketAddress)
```

**Comment by peter-evans** [comment]
You can add the secret `ACTIONS_STEP_DEBUG` set to `true`.

See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

**Comment by tijlleenders** [comment]
Thanks Peter,
That did the trick for the debugging.

Sorry to have bothered you with this.
I did use that page but didn't scroll down all the way. ** shame **
So I only set the ```ACTIONS_RUNNER_DEBUG``` secret to ```true``` ...
